### ISSUE TITLE
Won't build please help

### ISSUE THREAD

**Issue by Noob-Master-XD** [C3RV1/UndertaleNDS#11]
![image](https://user-images.githubusercontent.com/101499412/226000760-6b4d6fc4-d604-49b7-963d-dc931a769dc0.png)

**Comment by maxybooty** [comment]
how do i even make it work

**Comment by Noob-Master-XD** [comment]
> how do i even make it work

What do you mean?

**Comment by maxyboii1287149** [comment]
nvm i got working know

**Comment by randomuser1462** [comment]
> nvm i got working know

how did you get it working?
