### ISSUE TITLE
I can't patch the files correctly

### ISSUE THREAD

**Issue by Ralseidamagia** [C3RV1/UndertaleNDS#14]
I've followed all the steps but I simply can't get the .nds file. I've installed Ubuntu 18.04.6 on VirtualBox and I've also installed Python 3 and Pip 3, however, when I try to run the "patch_all.sh" file it shows me this error, what do I do? I've been trying to get this to work for a month and I can't figure it out, I need help.

![error](https://user-images.githubusercontent.com/129662567/229349798-2a3147ba-3eb2-4724-84fc-74716488a4b7.JPG)

**Comment by C3RV1** [comment]
It seems like you're using an old python version, probably 3.7? The scripts use python 3.9

**Comment by Ralseidamagia** [comment]
Let me see...

**Comment by Ralseidamagia** [comment]
Ok, I'm running 3.6.9, I'm going to try to update it to see if it works.

**Comment by Ralseidamagia** [comment]
It gives me this error :/
![thing](https://user-images.githubusercontent.com/129662567/229351099-9f382a4b-5b6f-4405-8807-2ec1904305da.JPG)

**Comment by C3RV1** [comment]
you should run patch_all.sh

**Comment by Ralseidamagia** [comment]
I finally figured it out by myself. Thanks for responding anyway!! :D
