### ISSUE TITLE
first screen of the game is not correct

### ISSUE THREAD

**Issue by lioree** [C3RV1/UndertaleNDS#19]
We just compiled and deployed your project to DSI XL and  3DS XL and we saw same behavior:
the first screen is showing the character off-
screen.
see attached photo. 
![WhatsApp Image 2023-05-24 at 16 33 33](https://github.com/C3RV1/UndertaleNDS/assets/34944753/709c722d-42b0-40ea-8fd1-be3715c08c67)

**Comment by C3RV1** [comment]
Ohhh my bad, that's something I use for debugging and it seems I left it in the code.

**Comment by C3RV1** [comment]
You should edit the file "source/main.cpp" and remove lines 43 and 44. Then build again the ROM and it should be back to normal.

**Comment by lioree** [comment]
Its working now.

My son will continue playing and we will update on issues.

Many thanks.

**Comment by C3RV1** [comment]
Great! Be aware that only around 15 minutes of gameplay have been programmed so far, so at some point you'll find yourselves unable to progress

**Comment by VelamyGH** [comment]
something about a parent making a github post for their child is really wholesome
