### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by godreborn** [C3RV1/UndertaleNDS#2]
I compiled the game, but I get a black screen upon opening.  you mentioned a python script called decrypt_all.py?  I found a shell script named that, but not a python one, so I used the shell script.  is the nitrofs or any other file supposed to go on the ds other than the nds file?

**Comment by C3RV1** [comment]
Oh yeah! Forgot to mention, but that black screen is for testing. Just press START on that screen and the game will start. Also, I meant the shell script `decrypt_all.sh`, not a python script. Thanks for pointing it out!

**Comment by godreborn** [comment]
thanks.  we have success.

**Comment by C3RV1** [comment]
Great! I'll update the code as soon as possible to remove that black screen.
