### ISSUE TITLE
Cant understand how to run patch_all.sh

### ISSUE THREAD

**Issue by carolsalice** [C3RV1/UndertaleNDS#20]
Sorry if I am bit of a noob but I cant figure out how to use the patch_all.sh file. I tried using it in python 3.10 and 3.8 but I keep getting syntax errors every time. I'm really not sure what I am supposed to do with it or what program I can use to launch it

**Comment by lioree** [comment]
Hi,
Hope this will help you.
I ran "history" on Ubuntu and got these steps:

<install ubuntu 22.04>
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.8
sudo apt install python3-pip
sudo apt install openssh-server
unzip UndertaleNDS-main.zip
mv data.win UndertaleNDS-main/
mv Undertale.nds.patch UndertaleNDS-main/
mv tools.zip.patch UndertaleNDS-main/
mv nitrofs.zip.patch UndertaleNDS-main/
cd UndertaleNDS-main/
./patch_all.sh
python3 tools/all.py
export DEVKITARM=/opt/devkitpro/devkitARM
export DEVKITPRO=/opt/devkitpro
make

**Comment by mfoxbr** [comment]
by running ./patch_all.sh i'm having the following prompts:

Traceback (most recent call last):
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/patch_files.py", line 3, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Traceback (most recent call last):
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/patch_files.py", line 3, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Traceback (most recent call last):
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/patch_files.py", line 3, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by lioree** [comment]
try:
pip3 install Crypto
./patch_all.sh

**Comment by mfoxbr** [comment]
Now I'm haviong this:

Traceback (most recent call last):
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/patch_files.py", line 44, in <module>
    main(sys.argv[1], "../data.win", sys.argv[2])
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/patch_files.py", line 30, in main
    cipher = AES.new(key, AES.MODE_EAX, nonce)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_EAX'. Did you mean: 'MODE_ECB'?
Traceback (most recent call last):
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/patch_files.py", line 40, in <module>
    main(sys.argv[1], "../data.win", sys.argv[2] + ".zip")
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/patch_files.py", line 30, in main
    cipher = AES.new(key, AES.MODE_EAX, nonce)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_EAX'. Did you mean: 'MODE_ECB'?

**Comment by mfoxbr** [comment]
Now it worked!

**Comment by mfoxbr** [comment]
I had to run as "sudo ./patch_all.sh". Now when running "python3 tools/all.py", I get:

Traceback (most recent call last):
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/all.py", line 3, in <module>
    from gmxToCfnt import compile_fonts
  File "/mnt/f/Downloads/UndertaleNDS-main/tools/gmxToCfnt.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by lioree** [comment]
I didn't had these, but try to install every python module that is missing, for example :
pip3 install PIL
./patch_all.sh

**Comment by mfoxbr** [comment]
I found it now, the name of the module, is actually "pillow"

**Comment by mfoxbr** [comment]
I'm stuck again. When I run "make", I get:

Makefile:9: /opt/devkitpro/devkitpro/ds_rules: No such file or directory
make: *** No rule to make target '/opt/devkitpro/devkitpro/ds_rules'.  Stop.

I installed devkitpro using:
wget https://apt.devkitpro.org/install-devkitpro-pacman
chmod +x ./install-devkitpro-pacman
sudo ./install-devkitpro-pacman

**Comment by mfoxbr** [comment]
I had it right now. Actually I had run:
export DEVKITARM=/opt/devkitpro/devkitARM
export DEVKITPRO=/opt/devkitpro

The second line was directing to the wrong folder. So I just had to run "export DEVKITARM=/opt/devkitpro/devkitARM" again to correct it.

Now I could build the game. Thank you @lioree for the support!

**Comment by carolsalice** [comment]
Ok followed your comments and it worked for me thanks everyone :) <3
