### ISSUE TITLE
Game version not supported

### ISSUE THREAD

**Issue by DaRkProaso** [C3RV1/UndertaleNDS#23]
i'm trying to use the patch_all.sh but this message goes and then the rest doesn't work
![image](https://github.com/C3RV1/UndertaleNDS/assets/122731819/fa7f3036-ec02-4c3f-84ef-e1c4bed69b6b)

**Comment by essayharper** [comment]
go into a hex editor and change the header to match the one on the patches, you may possibly have a cracked version

**Comment by DaRkProaso** [comment]
I forgot I modded the game that's why it didn't work, problem solved

**Comment by 5appdata5** [comment]
How to change the header?

**Comment by IHatenam3** [comment]
I bought the game on switch so i am using a cracked data.win,what can i do?

**Comment by essayharper** [comment]
> I bought the game on switch so i am using a cracked data.win,what can i do?

https://store.steampowered.com/app/391540/Undertale/

**Comment by IHatenam3** [comment]
> > I bought the game on switch so i am using a cracked data.win,what can i do?
> 
> https://store.steampowered.com/app/391540/Undertale/

:(
