### ISSUE TITLE
I need help with makefile

### ISSUE THREAD

**Issue by sorakaiz** [C3RV1/UndertaleNDS#27]
whenever I use the make command this happens:

bash: line 1: arm-none-eabi-g++: command not found
make[1]: *** [/mnt/c/devkitpro/devkitARM/base_rules:34: MainMenu.o] Error 127
make: *** [Makefile:156: build] Error 2

if anyone know how to fix it pls tell me.

**Comment by godreborn** [comment]
try pacman -Syu nds-dev

**Comment by godreborn** [comment]
btw, you're supposed to use the patch_all.sh file.  it should create the nds.  let me check if make works: 
![image](https://github.com/C3RV1/UndertaleNDS/assets/13548481/c3284a9c-9bb1-463b-9f41-20c4ea5e35b4)

**Comment by godreborn** [comment]
![image](https://github.com/C3RV1/UndertaleNDS/assets/13548481/da5c460b-d703-43ef-aa3e-e25e5e785b9c)

yep, works in msys.  I couldn't get the make file detected in cmd prompt for some reason.  this is the second time this has happened.  I need to investigate.

**Comment by godreborn** [comment]
![image](https://github.com/C3RV1/UndertaleNDS/assets/13548481/cff5f2ab-db8c-47a4-9979-a7e7758ea1e0)

btw, I fixed the make issues in cmd prompt.  it was due to an ev problem, not related to the project.

**Comment by sorakaiz** [comment]
ty it works now

**Comment by godreborn** [comment]
you do have to run the .sh file, which makes the .nds anyway, before you can run make or it does error due to missing nitrofs.  glad you got it working though.
