### ISSUE TITLE
no save data??

### ISSUE THREAD

**Issue by bonzijuse** [C3RV1/UndertaleNDS#31]
running this in TWIlight menu on my o3ds, got to the leafy pile save after toriel leaves last night, but when i started again it brought me back to the new game screen. anything i mightve done wrong or is this just a limitation of the port?

**Comment by ThomasRawnsleyDev** [comment]
By what I can tell, it's just a limitation. Saving will probably be implemented at some point, but the port is still in very early development and will need a lot more things added first.

**Comment by C3RV1** [comment]
saving in twlmenu is already implemented in the dev branch, but hasn't still been released in the main branch
