### ISSUE TITLE
Emulation Errors

### ISSUE THREAD

**Issue by D35P4C1T0** [C3RV1/UndertaleNDS#36]
What I'm using:
- Arch Linux
- melonDS 0.9.5
- compiled the rom straight from source

SHA256 of the rom file: `7cfdd73b9c1374c1aea6bb96866e54b3bb4bc8c6a35a236d4e1b67a02364b562`
MD5 of the rom file: `72ab08a002d4ab776121e88499acec5b`

Untested on real hardware.
Logs of melonDS crashing are attached to this issue.
[logs.txt](https://github.com/C3RV1/UndertaleNDS/files/14001812/logs.txt)

Also, saying to 'patch' when in fact you are just using the original game's `data.win` file as a key to decrypt the encrypted ROM/tools/nitrofs is rather clumsy in my opinion.

The original assets don't seem to be required during the compile phase, as they come included in the nitrofs file.

Edit: I had to use either melonDS 0.9.1 with DS bios files or an R4/TwilightMenu

**Comment by C3RV1** [comment]
https://github.com/melonDS-emu/melonDS/issues/1848
