### ISSUE TITLE
make command doesn't work

### ISSUE THREAD

**Issue by LukaTV939** [C3RV1/UndertaleNDS#41]
I've seen closed issues about this which "solve" the problem, but that's really not the case for me.

I followed the readme as accurately as possible and I always get the same error:
`make: *** No targets specified and no makefile found.  Stop.`

This is what I did:
1. Download 4 files from the release
2. Copied data.win from undertale folder
3. Selected data.win in the patcher
4. Selected 3 .patch files
5. Opened the directory in cmd
6. typed `python3 tools/all.py`
7. after that typed `make`
8. I get the same error

**Comment by C3RV1** [comment]
Have you downloaded the Github repository too? (not only the release files)

**Comment by Lick-rocks** [comment]
Im dealing with the same issue. No idea how to make the rom. I've done everything that's explained but is very confusing. I think a video of someone accomplishing the download successfully would be helpful. When I run the makefile on MSYS it says that there is no such file or directory so I tried Makefile_blocksds and most lines of code say command not found. Im silly what am I doing wrong? please help I bought undertale just for this lol.

**Comment by LukaTV939** [comment]
> Have you downloaded the Github repository too? (not only the release files)

Hi, sorry for the late reply

I don't think I did because you didn't really disclosed that in README, which is probably what you meant by "root directory of the project"
I'll try making from the repo itself and see if that works. If the main branch doesn't work I'll try dev

**Comment by LukaTV939** [comment]
ok I'm not gonna try and compile the code myself anymore
I did the patch from release and also ran patcher.py which is literally same, and I think the .patch would just be the same
So I'm just gonna redirect to #50 which is the issue I currently have
