### ISSUE TITLE
In game bug: can't move objects

### ISSUE THREAD

**Issue by tcsenpai** [C3RV1/UndertaleNDS#43]
I built the game using the last release with patcher.exe and got a working nds.

Besides the fact that using an R4 it does not load on a nintendo DS lite (can't access save file), I am running it with TWiLighT Menu++ on a 3DS. 

The game runs, but when I encounter the first object to push (the rock in the first room when you have to move it to the button), I can't seem to be able to push it no matter what I do.

Update: this happens also with the 0.0.4

Is that a known bug?

**Comment by C3RV1** [comment]
That is the end of the port at the moment. There is no more content, pushing the rock isn't implemented.
