### ISSUE TITLE
Issue with new patching system

### ISSUE THREAD

**Issue by godreborn** [C3RV1/UndertaleNDS#7]
hey, this is godreborn from temp.  I just tried your new patches, but there's a problem.  it will only let me apply one of them.  I'm assuming it's looking for the right checksum, which has obviously changed after patching it once.  I think all three are looking for an unmodified file.  I'm not sure how to proceed.

**Comment by C3RV1** [comment]
All of them should be applied to an unmodified file as they result in different project files. Sorry about not specifying it on the README. I'll add it soon.

**Comment by godreborn** [comment]
do you mean we need three data.win files?  because it will not let me apply more than one patch.  it doesn't matter which patch it is.

**Comment by C3RV1** [comment]
yes. just make 3 copies and apply a different patch for each of them. however, if you just want to play the game without building it, patching just for the Undertale.nds file will be enough

**Comment by godreborn** [comment]
here's what happens if I try extracting the assets:

![image](https://user-images.githubusercontent.com/13548481/198371644-d132318f-f8cd-42e1-a140-b81564dbeed3.png)

**Comment by C3RV1** [comment]
To get those missing files, needed for building, you need to patch a `data.win` with `tools.zip.ups` to get `tools.zip`. This zip file contains the files needed for building the game, which need to be extracted into the tools directory directly (like "merging" the content of the zip file with the contents of the folder). Then, you should be able to run `tools/all.py`. However, if you're just looking to test the ROM, there's no need for that. Undertale.nds should work directly on an emulator.

**Comment by godreborn** [comment]
after you patch it, you should get a tools.zip?  I did not.

**Comment by C3RV1** [comment]
I think so, you should get a tools.zip by patching it with tools.zip.ups

**Comment by godreborn** [comment]
I did not get anything.

**Comment by godreborn** [comment]
I figured out the problem.  it doesn't rename the data.win.  the data.win is the zip file.

**Comment by C3RV1** [comment]
Ohhh okay, I didn't know about that behaviour

**Comment by godreborn** [comment]
there's still a problem.  I did both nitrofs and tools, then I patched the win file with its patch.  after that, I tried the python command, and this happened:

![image](https://user-images.githubusercontent.com/13548481/198376727-905a25aa-d9c9-44e2-a2e2-d7d4e50f6b31.png)

**Comment by C3RV1** [comment]
oh god I forgot to remove the debug prints... well until I get that fixed on the next release, you could edit pngToCbgf.py to remove all prints, which should correct this issue

**Comment by godreborn** [comment]
I renamed it to UndertaleNDS.nds like the ups shows, and it seemed to go through, but I'm not sure where the finished file is located:

![image](https://user-images.githubusercontent.com/13548481/198377341-64374ee9-ccd7-467c-82ae-43c78088c308.png)

**Comment by C3RV1** [comment]
There's no need to do all of this if you just wish to play, are you sure you need to build it yourself?

**Comment by godreborn** [comment]
just trying to learn how to build it with the new patches.  the original ones I didn't have a problem with.  also, a couple people in your thread on temp wanted to know how to build it.  that's when I noticed the instructions were different.

**Comment by C3RV1** [comment]
mhm I know, the other instructions were more automated. right now I don't know exactly what's the issue, and I don't have the time right now to work on it. I'll work on better and more straightforward instructions when I can, sorry :(

**Comment by VelamyGH** [comment]
new (working) patching system, u can probably close this now me thinks

**Comment by godreborn** [comment]
yeah, works fine for me with the new patching system:

![image](https://user-images.githubusercontent.com/13548481/217881279-3b5d27fb-5f85-4447-9116-eecbd3323a0b.png)
