### ISSUE TITLE
Applying patches and creating undertale.nds

### ISSUE THREAD

**Issue by Bovemax** [C3RV1/UndertaleNDS#8]
Hi, I was wondering if you could help explain better on how to use ups patches, and how to eventually get an undertale.nds file from patching data.win. Also, if you don't mind, could you possibly create a tutorial video on how to apply these patches?

Thanks!

**Comment by C3RV1** [comment]
Hello!
Currently the system is broken and it doesn't seem like applying the patches can yield a usable undertale.nds file. I'll work on providing a solution soon, but lately I've been really busy on a personal level and I haven't had time to work on it. I'll fix it and I'll provide better instructions as soon as I can.

Sorry for not being able to solve your problem

**Comment by Bovemax** [comment]
It's ok, I was actually able to compile by reading one of the recent issues. The only problem is that Flowey is extremely slow. If there is any specific DS emulator that I should be using or any settings that I should set, please let me know.
This is amazing how you're able to port undertale, keep up the good work!
Thanks!

**Comment by C3RV1** [comment]
what emulator are you using? I tested with melonds and it ran fine @Bovemax

**Comment by trecobre** [comment]
It's kinda dumb question but do you think it's possible to play on a physical DS with an r4 ? If you don't know i'll just wait the fix for applying the fix and test it for you.

**Comment by C3RV1** [comment]
Yes! It's perfectly compatible with an original Nintendo DS. I don't know however about the compatibility with an R4, but it should work too I suppose.
